version: "3.8"

# ════════════════════════════════════════════════════════
#  docker-compose-api.yml 
#  Lance l'API Flask + Dashboard sur http://localhost:5000
#
#  LANCEMENT :
#    docker-compose -f docker-compose-api.yml up -d --build
# ════════════════════════════════════════════════════════

services:

  api:
    build: ./api
    container_name: recommandation_api
    ports:
      - "5000:5000"
    volumes:
      # Monte le dossier output/ du projet 
      - ./output:/app/../output:ro
      # Monte resultats_rmse.txt 
      - ./resultats_rmse.txt:/app/../resultats_rmse.txt:ro
      # Monte le rapport Airflow 
      - ./output/rapport_monitoring.json:/app/../output/rapport_monitoring.json:ro
    restart: unless-stopped

networks:
  default:
    name: projet-recommandation_big_data_default
    external: true